# Generated by Django 5.2.9 on 2025-12-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_backup_codes_customuser_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_enebled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_secret',
        ),
    ]
